{{- if and .Values.api.enabled .Values.api.database.password (not .Values.api.database.existingSecret) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "velocity.api.fullname" . }}-db
  labels:
    {{- include "velocity.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
stringData:
  {{ .Values.api.database.passwordKey }}: {{ .Values.api.database.password | quote }}
{{- end -}}
