{{- if and .Values.api.enabled .Values.api.typesense.enabled (eq (default "" .Values.api.typesense.existingSecret) "") -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "velocity.api.fullname" . }}-typesense
  labels:
    {{- include "velocity.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
stringData:
  api_key: {{ .Values.api.typesense.apiKey | quote }}
{{- end -}}
