{{- if and .Values.archiveWorker.enabled .Values.archiveWorker.database.password (not .Values.archiveWorker.database.existingSecret) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "velocity.archiveWorker.fullname" . }}-db
  labels:
    {{- include "velocity.labels" . | nindent 4 }}
    app.kubernetes.io/component: archive-worker
stringData:
  {{ .Values.archiveWorker.database.passwordKey }}: {{ .Values.archiveWorker.database.password | quote }}
{{- end -}}
