{{- if and .Values.operator.enabled .Values.operator.database.password (not .Values.operator.database.existingSecret) -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "velocity.operator.fullname" . }}-db
  labels:
    {{- include "velocity.labels" . | nindent 4 }}
stringData:
  password: {{ .Values.operator.database.password | quote }}
{{- end -}}
