{{- if and .Values.portal.enabled .Values.portal.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "velocity.portal.fullname" . }}
  labels:
    {{- include "velocity.labels" . | nindent 4 }}
    app.kubernetes.io/component: portal
  {{- with .Values.portal.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.portal.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.portal.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.portal.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: {{ .path | default "/" }}
            pathType: {{ .pathType | default "Prefix" }}
            backend:
              service:
                name: {{ include "velocity.portal.fullname" $ }}
                port:
                  number: {{ $.Values.portal.service.port }}
    {{- end }}
{{- end -}}
