apiVersion: v2
name: velocity
description: Velocity — schema-driven Kubernetes-native backend platform.
type: application
version: 0.1.6
appVersion: "0.1.6"
home: https://velocity.kinarix.com
sources:
  - https://github.com/kinarix/velocity
keywords:
  - kubernetes
  - operator
  - schema-driven
  - rust
maintainers:
  - name: Kinarix
    url: https://velocity.kinarix.com
